modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "rpg_battle_gear"
version = "${version}"
displayName = "RPG Battle Gear"
authors = "Bandit-Bytes"
description = '''
RPG Style Armor and items.
'''
#logoFile = ""

[[dependencies.rpg_battle_gear]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rpg_battle_gear]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rpg_battle_gear]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "rpg_battle_gear.mixins.json"
